/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Detect */
        post: operations["detect_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DetectRequest */
        DetectRequest: {
            /**
             * Layers
             * @description Layers to run, omit for all. May only narrow what the server runs, and must always include 'deterministic': the catalog layer costs microseconds and its checksum spans are what keep a model guess from displacing an identifier.
             */
            layers?: ("deterministic" | "ner")[] | null;
            /**
             * Text
             * @description Text to scan, in original coordinates
             */
            text: string;
        };
        /** DetectResponse */
        DetectResponse: {
            /**
             * Layers Run
             * @description Layers that actually ran for this request
             */
            layers_run: ("deterministic" | "ner")[];
            /** Spans */
            spans: components["schemas"]["Span"][];
            /**
             * Version
             * @description Digest of the weights and catalogs that produced these spans. A caller that caches spans must key them by this: it changes whenever the same text would detect differently.
             */
            version: string;
        };
        /**
         * ErrorDetail
         * @description Body of a fail-closed response: a reason, never the submitted text.
         */
        ErrorDetail: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ner */
            ner: boolean;
            /** Ner Off Reason */
            ner_off_reason: string | null;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** Span */
        Span: {
            /**
             * Boosted
             * @default false
             */
            boosted: boolean;
            /** Confidence */
            confidence: number;
            /**
             * End
             * @description Character offset in the original text, exclusive
             */
            end: number;
            /** Entity Type */
            entity_type: string;
            /** Recognizer */
            recognizer: string;
            /**
             * Start
             * @description Character offset in the original text, inclusive
             */
            start: number;
            /** Tier */
            tier: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    detect_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description A requested layer cannot run; the reason is named. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
